### PR TITLE
Implement getInt

### PR DESCRIPTION
**Pull request by donnapep**
Return a default value for `rsH` in `getInt` function.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Please review. I need to return a specific value for `rsH`. I added a hardcoded value because I can't figure out any other way to do this. Any ideas? Thx.

**Comment by stulees** [comment]
@donnapep So I understand, for what reason do you need a specific value?

**Comment by donnapep** [comment]
@stulees I need to set it to a value larger than my content so that it won't scroll for the PUD failover setting. But I also just realized that there should also be a test for when the content does scroll, so ideally, this value should be configurable. Ugh.

**Comment by stulees** [comment]
@donnapep Ah, yeah, sounds like hard coding the value should be avoided.

**Comment by donnapep** [comment]
@stulees Please review again. Thx.

**Comment by stulees** [comment]
@donnapep :+1:

**Pull request merged**
