### PR TITLE
Upgrade karma-phantomjs-launcher to latest

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. This appears to resolve the issue with PhantomJS not starting on Mac OS Sierra. Thx.

**Comment by stulees** [comment]
@donnapep Any idea if this will cause an issue for pre Sierra (El Capitan)? Do we need to upgrade?

**Comment by donnapep** [comment]
@stulees You'll have to try it out, but it resolves the issue I started experiencing this morning.

**Comment by stulees** [comment]
@donnapep 👍

**Comment by donnapep** [comment]
@stulees Once I upgrade Video Widget, you can try running the tests and if there are any issues, let's discuss next steps. Thx.

**Comment by stulees** [comment]
@donnapep Sounds good

**Pull request merged**
