### PR TITLE
Add timer to rise-storage mock

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees Part of the solution to our refresh woes. Please review. Thx.

**Comment by stulees** [comment]
@donnapep So `startTimer` and the use of 5 seconds is a workaround for testing the refresh without using `sinon.useFakeTimers()`. Do I have this right?

**Comment by donnapep** [comment]
@stulees I'm not going to use sinon at all for refreshing from Storage actually. You'll see what I plan to do when I'm able to do a PR for the Image Widget.

**Comment by donnapep** [comment]
@stulees So yes, I think that's what you've just said.

**Comment by stulees** [comment]
@donnapep Okay :+1:

**Pull request merged**
