### PR TITLE
Changes to logger mock regarding ids

### PR DESCRIPTION
**Pull request by stulees**
- Logger mock removing the retrieval of company and display ids to follow recent updates to Logger module in widget-common

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi @donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees I think the version should be 1.0.0 since it's a breaking change.

**Comment by stulees** [comment]
@donnapep Updated the version

**Comment by donnapep** [comment]
:+1:

**Pull request merged**
