### PR TITLE
Forcing protractor 3.1.1 to be used due to issues with 3.2

### PR DESCRIPTION
**Pull request by stulees**
- protractor 3.2 has issues - https://github.com/angular/protractor/issues/3034

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi @alex-deaconu Please review, this should fix our build timeout issues on CCI when tests are being run.

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: cheers

**Comment by alex-deaconu** [comment]
@stulees just ran into the same issue. Here's my version of the fix: https://github.com/Rise-Vision/widget-tester/compare/chore/update-protractor?expand=1.

Basically, I'm updating the `gulp-protractor` version which automatically forces newer Protractor to be used.

@rodrigopavezi FYI. Thoughts? Thanks.

**Comment by stulees** [comment]
@alex-deaconu From what I can tell the problem is with `protractor` latest version 3.2 itself which is the version getting installed by widget-tester in CCI builds. There's been a couple issues logged against it in the last few hours, the main one being this one -  https://github.com/angular/protractor/issues/3034 which looks to be why protractor can't be found when our tests get run in CCI.

**Comment by alex-deaconu** [comment]
@stulees `gulp-protractor` 2.0 forces `protractor:~2.1.1` version by default: https://github.com/mllrsohn/gulp-protractor/blob/master/package.json.

This way we stay up to date with library versions.

Thanks.

**Comment by stulees** [comment]
@alex-deaconu Ah I see now that `gulp-protractor` 0.0.11 specifies "*" as the version https://goo.gl/OJBOmr . Good call on the change. 

I'll close this PR, can you open a PR for your branch fix? Cheers

**Pull request closed without merging**
