### PR TITLE
Revert "fix sinon version"

### PR DESCRIPTION
**Pull request by alex-deaconu**
Reverts Rise-Vision/widget-tester#65

### CODE REVIEW

**Comment by stulees** [comment]
@alex-deaconu @rodrigopavezi Does this PR need a review? Does it need merging? Thanks

**Comment by alex-deaconu** [comment]
@stulees good question. We initially made this PR to fix an issue with `sinon`. However, it appears the issue they introduced in their new version is now fixed. I just need to verify, something which I've been meaning to do, but am tied up with something else. 

So review at will. Thanks!

**Comment by stulees** [comment]
@alex-deaconu Okay thanks for clarifying. Sounds like this PR can just be closed then once you've verified the new version works.

**Comment by alex-deaconu** [comment]
@stulees if by closed you mean merged, then yes. Will verify shortly. Thanks.

**Comment by alex-deaconu** [comment]
@stulees @rodrigopavezi tested this PR with a CH commit - it worked. Will merge. Thanks!

**Pull request merged**
